name: reddit_bel_ham
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  any_link_preview: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6  
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  video_player: ^2.8.5
  file_picker: ^8.0.0+1
  http: ^1.2.1
  timer_count_down: ^2.2.0
  dropdown_button2: ^2.3.9
  flutter_link_previewer: ^3.2.2
  url_launcher: ^6.0.9
  clipboard: ^0.1.3
  
  shared_preferences:
  jwt_decoder:
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  loading_indicator: ^3.1.1
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  modal_progress_hud_nsn: ^0.5.1
  mockito: ^5.4.4
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/elham_final_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
