name: Flutter Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
         smtp-server: smtp.gmail.com
         smtp-port: 465
         smtp-secure: true
         from-email: ${{ secrets.DEVOPS_EMAIL }}
         to-email: ${{ secrets.DEVOPS_EMAIL }},${{ secrets.SUB_TEAM_LEADER }},${{ secrets.TEAM_LEADER }}
         username: ${{ secrets.DEVOPS_EMAIL }}
         password: ${{ secrets.DEVOPS_PASSWORD }}
         subject: Test Email
         body: This is a test email sent from GitHub Actions.
         html: |
           <h1>This is a test email</h1>
           <p>Test Paragraph</p>