name: Flutter Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.x'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run Flutter Test
        run: flutter test

      - name: Send Email
        if: always()
        uses: hilarion5/send-mail@v1
        with:
           smtp-server: smtp.gmail.com
           smtp-port: 465
           smtp-secure: true
           from-email: ${{ secrets.DEVOPS_EMAIL }}
           to-email: ${{secrets.TEAM_LEADER }},${{secrets.SUB_TEAM_LEADER }}
           username: ${{ secrets.DEVOPS_EMAIL }}
           password: ${{ secrets.DEVOPS_PASSWORD }}
           subject: "Mabrooookkk!! SOGHEL 10/10"
           body: ${{ github.event_name }} event on ${{ github.repository }} triggered by ${{ github.actor }} at ${{ github.event.head_commit.timestamp }}